### ISSUE TITLE
Lightbox Navigation Arrows?

### ISSUE THREAD

**Issue by superscotty19** [machwatt/sf_filecollection_gallery#84]
Hi,

First of all, congratulations on building the best file collection extension! I am implementing it alongside perfectlightbox on TYPO3 6.2LTS (I know, it's older but it's got a pile of customizations that break with 8.7). Everything is working but the lightbox does not have any navigation arrows. Rather, the user must click an item, enlarge, close, then pick another. Perhaps this is a lightbox question, but is it possible to have arrows on the enlarged image to go to the next without having to close the enlarged image first?

Thanks,
-Scott.

**Comment by superscotty19** [comment]
Update: perfectlightbox has nav buttons, but they're set to "display: none" automatically. I don't know if this is a conflict with your extension of a misconfiguration with perfectlightbox.

**Comment by superscotty19** [comment]
Update: tested on another page using "text & images" CE -> lightbox nav arrows works fine. The difference is, the text & image CE has "click to enlarge" and "lightbox" as an option, whereas this extension only has "enable lightbox". Lightbox is triggered, but it's not all functioning.

**Comment by derhansen** [comment]
Thanks for your feedback. Sadly, I do not know, how ext:perfectlightbox integrates with TYPO3 / your website, but usually you do not need to configure anything in order to get a lightbox and image grouping/gallery up and working.

Please check, if ext:perfectlightbox needs additional settings for the grouping/gallery feature. Also check, that your Template for this extension contains all requirements of the lighbox you use of ext:perfectlightbox 

As an alternative, you could try ext:cl_jquery_fancybox, which I have used in other projects together with this extension without the need to change any template or JavaScript.

**Comment by superscotty19** [comment]
Thanks for the quick and thorough reply!

 I was thinking the same as you, which is why I tested on a different page on same site. Everything worked. Also, when I look at the source on a page with your extension, I can see the nav button code but they're disabled (which tells me that perfect lightbox doesn't think there are any photos to go next /prior to).  So, it appears that perfect lightbox and your extension don't play well together.

Thanks for recommending an alternative. I looked into it and sadly it only supports T3 7+ (I'm still in 6.2 for this install due to some custom work that was done).

**Comment by derhansen** [comment]
Version 3.0.7 of ext:cj_jquery_fancybox is compatible with TYPO3 6.2 (see: https://extensions.typo3.org/extension/cl_jquery_fancybox/) - you can install this version using the TYPO3 Extension manager

**Comment by superscotty19** [comment]
Yes! That did it! Specifically:
- I disabled perfectlightbox in T3 template constants with plugin.perfectlightbox >
- I installed cl_jquery_fancybox 3.0.7 for T3 6.2

Thank you!!!!!!!!!!!!

**Comment by derhansen** [comment]
Great it works for you now.
